[project]
name = "wikipedia-usas-processing"
version = "0.1.0"
authors = [
    { name = "UCREL Research Centre", email = "ucrel@lancaster.ac.uk" },
]
license = "Apache-2.0"
license-files = [
    "LICENSE",
]
description = "Add your description here"
requires-python = ">=3.13, <3.15"
dependencies = [
    "datasets>=4.8.4",
    "datatrove[io,processing]==0.9.0",
    "mistune>=3.2.0",
    "pip>=26.0.1",
    "pymusas>=0.4.0",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "rich>=14.3.3",
    "spacy>=3.8.14",
    "spacy-curated-transformers>=0.3.1",
    "typer>=0.24.1",
    "usas-validator",
]

[dependency-groups]
dev = [
    "coverage>=7.13.5",
    "pytest>=9.0.2",
    "ruff>=0.15.7",
    "ty>=0.0.26",
]

[build-system]
requires = [
    "uv_build>=0.9.6,<0.12.0",
]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "wikipedia_processing"
module-root = ""

[project.readme]
file = "README.md"
content-type = "text/markdown"


[tool.ruff.lint]
# Enable the isort rules.
extend-select = ["I"]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [
    "tests",
    "wikipedia_processing",
]
addopts = "--doctest-modules"
doctest_optionflags = ["NORMALIZE_WHITESPACE"]

[tool.coverage.run]
branch = true
source = [
    "wikipedia_processing"
]
command_line = "-m pytest"

[tool.coverage.report]
show_missing = true
