from typing import Iterable, cast

import spacy
from datatrove.data import Document, DocumentsPipeline
from datatrove.pipeline.base import PipelineStep
from usas_validator.utils import (
    keep_valid_usas_tags,
    load_usas_mapper,
    mwe_labels_from_pymusas_indexes,
)

from wikipedia_processing.models_install import Languages as ModelInstallLanguages
from wikipedia_processing.models_util import get_language_tagger


class TokenPyMUSASAnnotator(PipelineStep):
    name = "🏷 Token + PyMUSAS Tag/MWE"
    type = "🏷 - ANNOTATE"

    def __init__(self, wikipedia_language_code: str):
        super().__init__()
        _language = getattr(ModelInstallLanguages, wikipedia_language_code, None)
        supported_languages = list(ModelInstallLanguages)
        if _language is None:
            raise ValueError(f"Invalid language code: {wikipedia_language_code!r} Supported languages: {supported_languages!r}")
        self.language = cast(ModelInstallLanguages, _language)
        self._nlp = None  # lazy-loaded per worker process

        usas_tags_to_filter_out = set({"Z99"})
        self.valid_usas_tags = set(load_usas_mapper(None, usas_tags_to_filter_out).keys())

    def _load_model(self) -> spacy.Language:
        if self._nlp is None:
            # disable components you don't need for speed (e.g. parser, ner)
            self._nlp = get_language_tagger(self.language)
        return self._nlp


    def get_sentences(self, doc: Document) -> Iterable[str]:
        sentence_start_end_indexes = doc.metadata.get("start_end_sentence_character_indexes", None)
        if sentence_start_end_indexes is None:
            raise ValueError(f"{self.name} requires `start_end_sentence_character_indexes` "
                                "within each document's metadata of which this can be generated by "
                                "the `SentenceSplitterAnnotator` pipeline step")
        for start_index, end_index in sentence_start_end_indexes:
            yield doc.text[start_index: end_index]

    def run(self, data: DocumentsPipeline, rank: int = 0, world_size: int = 1) -> DocumentsPipeline:
        nlp = self._load_model()

        for doc in data:
            doc = cast(Document, doc)
            sentence_tokens = []
            sentence_tags = []
            sentence_mwe_labels = []
            number_tokens = 0
            number_tagged_tokens = 0
            number_pymusas_tags = 0
            number_mwes = 0

            with self.track_time():
                for sentence in self.get_sentences(doc):
                    sentence = sentence.strip()
                    tokens = []
                    tags = []
                    mwe_labels = []
                    
                    # Some sentences do not contain any text content, in these
                    # cases some of the spaCy pipelines will fail, but to keep
                    # number of values in the tokens etc lists and sentence indexes 
                    # list the same we append an empty token list for empty sentences
                    if sentence:
                        all_pymusas_mwe_indexes: list[list[tuple[int, int]]] = []
                        for token in nlp(sentence):
                            tokens.append(token.text)
                            pymusas_tags = token._.pymusas_tags
                            all_pymusas_mwe_indexes.append(token._.pymusas_mwe_indexes)

                            most_likely_pymusas_tag: str = ""
                            if pymusas_tags and len(pymusas_tags) > 0:
                                most_likely_pymusas_tag = pymusas_tags[0]
                            else:
                                tags.append([])
                                continue

                            valid_pymusas_tags = keep_valid_usas_tags(most_likely_pymusas_tag, self.valid_usas_tags)
                            valid_most_likely_pymusas_tags: list[str] = []
                            if valid_pymusas_tags and len(valid_pymusas_tags) > 0:
                                valid_most_likely_pymusas_tags = valid_pymusas_tags[0].tag_strings
                                number_tagged_tokens += 1
                            
                            number_pymusas_tags += len(valid_most_likely_pymusas_tags)
                            tags.append(valid_most_likely_pymusas_tags)
                    
                        number_sentence_tokens = len(tokens)
                        tmp_mwe_labels = mwe_labels_from_pymusas_indexes(all_pymusas_mwe_indexes)
                        
                        mwe_labels_json_serializable = []
                        number_mwes_in_sentence = 0
                        for mwe_labels in tmp_mwe_labels:
                            if mwe_labels:
                                number_mwes_in_sentence = max(mwe_labels)
                            mwe_labels_json_serializable.append(list(mwe_labels))
                        mwe_labels = mwe_labels_json_serializable
                        number_mwes += number_mwes_in_sentence

                        number_tokens += number_sentence_tokens
                    
                    sentence_tokens.append(tokens)
                    sentence_tags.append(tags)
                    sentence_mwe_labels.append(mwe_labels)
            doc.metadata["tokens"] = sentence_tokens
            doc.metadata["tags"] = sentence_tags
            doc.metadata["mwes"] = sentence_mwe_labels

            self.stat_update("tokens", value=number_tokens)
            self.stat_update("tagged tokens", value=number_tagged_tokens)
            self.stat_update("PyMUSAS tags", value=number_pymusas_tags)
            self.stat_update("MWEs", value=number_mwes)
            yield doc
