from typing import Iterable, cast

import spacy
from datatrove.data import Document, DocumentsPipeline
from datatrove.pipeline.base import PipelineStep
from usas_validator.utils import (
    keep_valid_usas_tags,
    load_usas_mapper,
    mwe_labels_from_pymusas_indexes,
)

from wikipedia_processing.models_install import Languages as ModelInstallLanguages
from wikipedia_processing.models_util import get_language_tagger


class TokenPyMUSASAnnotator(PipelineStep):
    """DataTrove pipeline step that tags document sentences with USAS tags and MWEs.

    For each sentence in a document (delimited by the
    "start_end_sentence_character_indexes" metadata produced by
    :class:`~wikipedia_processing.pipelines.sentence_splitting.SentenceSplitterAnnotator`)
    this step tokenizes the sentence with a language-specific spaCy + PyMUSAS
    pipeline, keeps each token's most likely tag if it is a valid USAS tag, and
    derives Multi-Word Expression (MWE) labels. Each document's metadata is
    updated in place with "tokens", "tags" and "mwes" lists (one entry per
    sentence), and step statistics are recorded for tokens, tagged tokens,
    PyMUSAS tags and MWEs.

    Attributes:
        name: Human-readable step name shown in DataTrove pipeline stats.
        type: DataTrove pipeline step category shown in DataTrove pipeline stats.
    """

    name = "🏷 Token + PyMUSAS Tag/MWE"
    type = "🏷 - ANNOTATE"

    def __init__(self, wikipedia_language_code: str, tag_mapper: dict[str, str] | None = None):
        """Initialize the annotator.

        Args:
            wikipedia_language_code: A Wikipedia language code (e.g. "en",
                "da") identifying a member of
                :class:`~wikipedia_processing.models_install.Languages`.
            tag_mapper: Optional mapping used to rename each valid USAS tag
                (e.g. to collapse fine-grained tags into a coarser set) after
                filtering. Tags with no entry in the mapping are kept
                unchanged. If None, no mapping is applied.

        Raises:
            ValueError: If wikipedia_language_code is not a supported
                language code.
        """
        super().__init__()
        _language = getattr(ModelInstallLanguages, wikipedia_language_code, None)
        supported_languages = list(ModelInstallLanguages)
        if _language is None:
            raise ValueError(f"Invalid language code: {wikipedia_language_code!r} Supported languages: {supported_languages!r}")
        
        self.language = cast(ModelInstallLanguages, _language)
        self._nlp = None  # lazy-loaded per worker process

        usas_tags_to_filter_out = set({"Z99"})
        self.valid_usas_tags = set(load_usas_mapper(None, usas_tags_to_filter_out).keys())

        self.tag_mapper: dict[str, str] = {}
        if tag_mapper is not None:
            self.tag_mapper = tag_mapper

    def _load_model(self) -> spacy.Language:
        if self._nlp is None:
            # disable components you don't need for speed (e.g. parser, ner)
            self._nlp = get_language_tagger(self.language)
        return self._nlp


    def get_sentences(self, doc: Document) -> Iterable[str]:
        """Yield the text of each sentence in a document using its precomputed boundaries.

        Args:
            doc: The document to split into sentences. Its metadata must
                contain "start_end_sentence_character_indexes", a list of
                (start, end) character offset tuples produced by
                :class:`~wikipedia_processing.pipelines.sentence_splitting.SentenceSplitterAnnotator`.

        Yields:
            The substring of doc.text for each (start, end) sentence
            boundary, in the order they appear in
            "start_end_sentence_character_indexes".

        Raises:
            ValueError: If doc.metadata has no
                "start_end_sentence_character_indexes" key.

        Examples:
            >>> from datatrove.data import Document
            >>> doc = Document(text="Hello world. Bye.", id="1", metadata={
            ...     "start_end_sentence_character_indexes": [(0, 12), (13, 17)]})
            >>> annotator = TokenPyMUSASAnnotator("en")
            >>> list(annotator.get_sentences(doc))
            ['Hello world.', 'Bye.']

            >>> list(annotator.get_sentences(Document(text="x", id="1")))
            Traceback (most recent call last):
                ...
            ValueError: 🏷 Token + PyMUSAS Tag/MWE requires `start_end_sentence_character_indexes` within each document's metadata of which this can be generated by the `SentenceSplitterAnnotator` pipeline step
        """
        sentence_start_end_indexes = doc.metadata.get("start_end_sentence_character_indexes", None)
        if sentence_start_end_indexes is None:
            raise ValueError(f"{self.name} requires `start_end_sentence_character_indexes` "
                                "within each document's metadata of which this can be generated by "
                                "the `SentenceSplitterAnnotator` pipeline step")
        for start_index, end_index in sentence_start_end_indexes:
            yield doc.text[start_index: end_index]

    # ty infers generator functions as `types.GeneratorType`, which it won't match against
    # `DocumentsPipeline`'s `NewType(Generator[Document, None, None] | None)` alias.
    def run(self, data: DocumentsPipeline, rank: int = 0, world_size: int = 1) -> DocumentsPipeline:  # ty: ignore[invalid-return-type]
        """Tag each document's sentences with USAS tags and MWE labels.

        Lazily loads the language-specific spaCy + PyMUSAS pipeline on first
        use, then for every document tokenizes each of its sentences (from
        :meth:`get_sentences`), keeps each token's most likely tag if it is a
        valid USAS tag (optionally renamed via `tag_mapper`), and derives MWE
        labels from the tagger's MWE index output. Sets
        doc.metadata["tokens"], doc.metadata["tags"] and
        doc.metadata["mwes"] to lists with one entry per sentence, and
        records "tokens", "tagged tokens", "PyMUSAS tags" and "MWEs" step
        statistics.

        NOTE: tokens identified as whitespace are dropped/removed.

        Args:
            data: An iterable of documents to annotate.
            rank: The rank of the current worker process (unused, present for
                DataTrove's PipelineStep interface).
            world_size: The total number of worker processes (unused, present
                for DataTrove's PipelineStep interface).

        Yields:
            Each input document, with its metadata updated in place to
            include "tokens", "tags" and "mwes".
        """
        nlp = self._load_model()

        for doc in cast(Iterable[Document], data):
            sentence_tokens = []
            sentence_tags = []
            sentence_mwe_labels = []
            number_tokens = 0
            number_tagged_tokens = 0
            number_pymusas_tags = 0
            number_mwes = 0

            with self.track_time():
                for sentence in self.get_sentences(doc):
                    sentence = sentence.strip()
                    tokens = []
                    tags = []
                    mwe_labels = []
                    
                    # Some sentences do not contain any text content, in these
                    # cases some of the spaCy pipelines will fail, but to keep
                    # number of values in the tokens etc lists and sentence indexes 
                    # list the same we append an empty token list for empty sentences
                    if sentence:
                        all_pymusas_mwe_indexes: list[list[tuple[int, int]]] = []
                        for token in nlp(sentence):
                            # Skip tokens that are whitespace
                            if token.is_space:
                                continue

                            tokens.append(token.text)
                            pymusas_tags = token._.pymusas_tags
                            all_pymusas_mwe_indexes.append(token._.pymusas_mwe_indexes)

                            most_likely_pymusas_tag: str = ""
                            if pymusas_tags and len(pymusas_tags) > 0:
                                most_likely_pymusas_tag = pymusas_tags[0]
                            else:
                                tags.append([])
                                continue

                            valid_pymusas_tags = keep_valid_usas_tags(most_likely_pymusas_tag, self.valid_usas_tags)
                            valid_most_likely_pymusas_tags: list[str] = []
                            if valid_pymusas_tags and len(valid_pymusas_tags) > 0:
                                valid_most_likely_pymusas_tags = valid_pymusas_tags[0].tag_strings
                                number_tagged_tokens += 1
                            
                            if self.tag_mapper:
                                valid_most_likely_pymusas_tags = [self.tag_mapper.get(tag, tag) for tag in valid_most_likely_pymusas_tags]
                            
                            number_pymusas_tags += len(valid_most_likely_pymusas_tags)
                            tags.append(valid_most_likely_pymusas_tags)
                    
                        number_sentence_tokens = len(tokens)
                        tmp_mwe_labels = mwe_labels_from_pymusas_indexes(all_pymusas_mwe_indexes)
                        
                        mwe_labels_json_serializable = []
                        number_mwes_in_sentence = 0
                        for mwe_labels in tmp_mwe_labels:
                            if mwe_labels:
                                tmp_largest_mwe_index = max(mwe_labels)
                                if tmp_largest_mwe_index > number_mwes_in_sentence:
                                    number_mwes_in_sentence = tmp_largest_mwe_index
                            mwe_labels_json_serializable.append(list(mwe_labels))
                        mwe_labels = mwe_labels_json_serializable
                        number_mwes += number_mwes_in_sentence

                        number_tokens += number_sentence_tokens
                    
                    sentence_tokens.append(tokens)
                    sentence_tags.append(tags)
                    sentence_mwe_labels.append(mwe_labels)
            doc.metadata["tokens"] = sentence_tokens
            doc.metadata["tags"] = sentence_tags
            doc.metadata["mwes"] = sentence_mwe_labels

            self.stat_update("tokens", value=number_tokens)
            self.stat_update("tagged tokens", value=number_tagged_tokens)
            self.stat_update("PyMUSAS tags", value=number_pymusas_tags)
            self.stat_update("MWEs", value=number_mwes)
            yield doc
